name: base
channels:
  - conda-forge
dependencies:
  - python
  - jupyterlab
  - nodejs
  - ipywidgets
  - widgetsnbextension
  - pythonocc-core
  - pythreejs
  - ifcopenshell
  - python-graphviz
  - pandas
  - geopandas
  - shapely
  - folium
  
